"""change chunk/encryption_key ids to text

Revision ID: 593b5a0f26a0
Revises: 0001
Create Date: 2026-07-21 17:30:42.633588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593b5a0f26a0'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'id',
               existing_type=sa.UUID(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('encryption_keys', 'id',
               existing_type=sa.UUID(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('file_chunks', 'chunk_id',
               existing_type=sa.UUID(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_chunks', 'chunk_id',
               existing_type=sa.Text(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('encryption_keys', 'id',
               existing_type=sa.Text(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('chunks', 'id',
               existing_type=sa.Text(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
