"""remove telegram_message_id from chunks table

Revision ID: bc3584e79ff6
Revises: 0002
Create Date: 2026-07-22 09:04:53.875174

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc3584e79ff6"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunks", "telegram_message_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks",
        sa.Column("telegram_message_id", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
