"""use uuid pk for chunks

Revision ID: c33362cbc2c1
Revises: 0003
Create Date: 2026-07-23 02:22:03.095341

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c33362cbc2c1"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chunks",
        "id",
        existing_type=sa.TEXT(),
        type_=sa.UUID(),
        postgresql_using="id::uuid",
        existing_nullable=False,
    )
    op.alter_column(
        "file_chunks",
        "chunk_id",
        existing_type=sa.TEXT(),
        type_=sa.UUID(),
        postgresql_using="chunk_id::uuid",
        existing_nullable=False,
    )
    op.create_foreign_key(None, "file_chunks", "chunks", ["chunk_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "file_chunks", type_="foreignkey")
    op.alter_column(
        "file_chunks", "chunk_id", existing_type=sa.UUID(), type_=sa.TEXT(), existing_nullable=False
    )
    op.alter_column(
        "chunks", "id", existing_type=sa.UUID(), type_=sa.TEXT(), existing_nullable=False
    )
    # ### end Alembic commands ###
