from typing import Protocol

from vaultfs.storage.interface import ChunkId, ChunkInfo


class MetadataRepository(Protocol):
    async def save(self, chunk_id: ChunkId, message_id: int, info: ChunkInfo) -> None: ...

    async def get_message_id(self, chunk_id: ChunkId) -> int: ...

    async def get_info(self, chunk_id: ChunkId) -> ChunkInfo: ...

    async def mark_deleted(self, chunk_id: ChunkId) -> None: ...
